### ISSUE TITLE
Issue with testcase execution 

### ISSUE THREAD

**Issue by shrivinayak** [schumilo/vUSBf#5]
I’m trying to fuzz Ubuntu1804 and have generated required configuration file. 

What's Working: 
- Payload execution on external VM (18.04) works and I'm able to see the kernel messages on dmesg
`python vusbf.py -eon 127.0.0.1 1235 panic_1.obj`

what's not working:
- Executing payload without external VM
`python vusbf.py -eo payload/panic_1.obj -o ubuntu1804.config -v1`
Issue: Testcase count stuck at 0 
link - [pastebin](https://pastebin.com/TzcLiQY0)

**Comment by shrivinayak** [comment]
Solved it. Issue was with the QEMU image snapshot.

**Comment by 0roman** [comment]
@shrivinayak my issue #6 is similar to yours. Have you an idea whats going wrong? Best regards.
